### ISSUE TITLE
Internal server error when trying to chart data in Wiretap

### ISSUE THREAD

**Issue by djflux** [djflux/Wiretap#1]
The following error occurs due to changes in database member functions in MW 1.39:

```
[Y91xkHcQnsljxjxbZPHcqAAAANU] /demo/index.php?title=Special:Wiretap&show=total-hits-chart&requestDebug Error: Call to undefined method Wikimedia\Rdbms\DatabaseMysqli::fetchRow()

Backtrace:

from /opt/htdocs/mediawiki/includes/libs/rdbms/database/DBConnRef.php(103)
#0 /opt/htdocs/mediawiki/extensions/Wiretap/SpecialWiretap.php(406): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#1 /opt/htdocs/mediawiki/extensions/Wiretap/SpecialWiretap.php(34): SpecialWiretap->totalsChart2()
#2 /opt/htdocs/mediawiki/includes/specialpage/SpecialPage.php(701): SpecialWiretap->execute(NULL)
#3 /opt/htdocs/mediawiki/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run(NULL)
#4 /opt/htdocs/mediawiki/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#5 /opt/htdocs/mediawiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#6 /opt/htdocs/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#7 /opt/htdocs/mediawiki/index.php(50): MediaWiki->run()
#8 /opt/htdocs/mediawiki/index.php(46): wfIndexMain()
#9 {main}
```

Fix like https://github.com/djflux/WatchAnalytics/commit/2ebe7286b82a2f5367713a6bc1e9c0bbb6e8de02

**Comment by djflux** [comment]
Updated DB code with commit d70a56562ecd01cd3dec7f9e639a7e8f2898aaae

This commit also comments out a section of code because it was causing out of memory errors with PHP 8.1.8. Since I didn't know what the code was doing and the charts and data for Wiretap were working without it, I checked it in. Maybe James or someone else can tell me what that code is doing. Otherwise it should be removed altogether.
